[build]
    command = "npm run build"
    publish = "build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[template.environment]
    REACT_APP_PROJECT_SERVER = "Your app's API server URL in the format of 'https://app.com'"
